version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_db:/var/lib/postgresql/data
    restart: always

#  spring-boot-application:
#    container_name: spring-boot-application
#    build: ./
#    depends_on:
#      - postgres_db
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 123
#    restart: always

volumes:
  postgres_db: